"use client";

import { FormEvent, useState } from "react";
import { toast } from "sonner";

export function WorkspaceSettings({ workspace, onSaved, onDeleted }: { workspace: { id: string; name: string; description?: string | null }; onSaved: () => Promise<void>; onDeleted: () => Promise<void> }) {
  const [pending, setPending] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [showDelete, setShowDelete] = useState(false);
  const [deletePending, setDeletePending] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setMessage(null); const form = new FormData(event.currentTarget); const response = await fetch(`/api/workspaces/${workspace.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), description: form.get("description") }) }); const result = await response.json(); setPending(false); if (!response.ok) { setMessage(result.error?.message ?? "Unable to update workspace."); toast.error("Workspace update failed"); return; } await onSaved(); setMessage("Workspace settings saved."); toast.success("Workspace settings saved successfully"); }
  async function confirmDelete() { setDeletePending(true); await onDeleted(); setDeletePending(false); }
  return <section className="max-w-2xl"><div className="mb-6"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[var(--saas-blue)]">Workspace preferences</p><h2 className="mt-1 text-2xl font-bold text-[var(--saas-navy)]">Settings</h2></div><form className="rounded-2xl border border-[var(--saas-line)] bg-white p-6 shadow-[0_12px_32px_rgba(31,41,79,0.04)]" onSubmit={submit}><div className="space-y-5"><label className="grid gap-2 text-sm font-semibold text-[var(--saas-navy)]">Workspace name<input className="h-11 rounded-xl border border-[var(--saas-line)] bg-slate-50 px-3 text-sm outline-none focus:border-[var(--saas-blue)] focus:bg-white focus:ring-4 focus:ring-blue-100" defaultValue={workspace.name} name="name" required /></label><label className="grid gap-2 text-sm font-semibold text-[var(--saas-navy)]">Description<textarea className="min-h-28 rounded-xl border border-[var(--saas-line)] bg-slate-50 px-3 py-3 text-sm outline-none focus:border-[var(--saas-blue)] focus:bg-white focus:ring-4 focus:ring-blue-100" defaultValue={workspace.description ?? ""} name="description" /></label></div>{message ? <p className="mt-4 rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{message}</p> : null}<div className="mt-6 flex justify-end"><button className="rounded-xl bg-[var(--saas-blue)] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50" disabled={pending} type="submit">{pending ? "Saving..." : "Save settings"}</button></div></form><div className="mt-6 rounded-2xl border border-red-200/70 bg-red-50/60 p-5 dark:border-red-300/20 dark:bg-red-950/20"><p className="text-sm font-bold text-red-700 dark:text-red-200">Danger zone</p><p className="mt-1 text-sm leading-6 text-red-700/70 dark:text-red-200/70">Deleting this workspace removes its projects, tasks, and members permanently.</p>{showDelete ? <div className="mt-4 rounded-xl border border-red-200 bg-white p-4 dark:border-red-300/20 dark:bg-[#142b21]"><p className="text-sm font-semibold text-[var(--saas-navy)]">Delete &quot;{workspace.name}&quot;?</p><div className="mt-3 flex gap-2"><button className="rounded-lg px-3 py-2 text-sm font-bold text-slate-500 hover:bg-slate-100 dark:hover:bg-white/10" disabled={deletePending} onClick={() => setShowDelete(false)} type="button">Cancel</button><button className="rounded-lg bg-red-600 px-3 py-2 text-sm font-bold text-white hover:bg-red-700 disabled:opacity-50" disabled={deletePending} onClick={() => void confirmDelete()} type="button">{deletePending ? "Deleting..." : "Delete workspace"}</button></div></div> : <button className="mt-4 rounded-lg border border-red-300 px-3 py-2 text-sm font-bold text-red-700 transition hover:-translate-y-0.5 hover:bg-red-600 hover:text-white dark:border-red-300/30 dark:text-red-200" onClick={() => setShowDelete(true)} type="button">Delete workspace</button>}</div></section>;
}